name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Debug Info
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Git status:"
          git status
      
      - name: Log in to GitHub Container Registry
        run: |
          echo "Logging into GitHub Container Registry..."
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Set repository name to lowercase
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build . --tag ghcr.io/${{ env.REPO_NAME }}:latest --no-cache
          echo "Docker image built successfully"
          docker images
          
      - name: Push Docker image
        run: |
          echo "Pushing Docker image to registry..."
          docker push ghcr.io/${{ env.REPO_NAME }}:latest
          echo "Docker image pushed successfully"