name: Docker Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      run: |
        set -e
        git init
        git remote add origin "https://github.com/${GITHUB_REPOSITORY}.git"
        git fetch --depth=1 origin "${GITHUB_REF}"
        git checkout -b working FETCH_HEAD
      shell: bash
    
    - name: Set up Docker
      run: |
        set -e
        docker version
        docker buildx version
        if ! docker buildx inspect default > /dev/null 2>&1; then
          docker buildx create --name default --use
        fi
      shell: bash
      
    - name: Log in to GitHub Container Registry
      run: |
        set -e
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      shell: bash

    - name: Set environment variables
      run: |
        echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      shell: bash
        
    - name: Build Docker image
      run: |
        set -e
        docker buildx build \
          --platform linux/amd64 \
          --tag "ghcr.io/${REPO_LOWER}/futures-trading-log:latest" \
          --tag "ghcr.io/${REPO_LOWER}/futures-trading-log:${{ github.sha }}" \
          --load \
          .
      shell: bash

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        set -e
        docker push "ghcr.io/${REPO_LOWER}/futures-trading-log:latest"
        docker push "ghcr.io/${REPO_LOWER}/futures-trading-log:${{ github.sha }}"
      shell: bash
        
    - name: Run Tests
      run: |
        set -e
        docker build -t futures-trading-log-test -f Dockerfile.test .
        docker run --rm futures-trading-log-test pytest tests/ -v --cov=. --cov-report=term-missing
      shell: bash