name: Docker Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      run: |
        git init
        git remote add origin https://github.com/${{ github.repository }}
        git fetch origin ${{ github.ref }}
        git checkout FETCH_HEAD
    
    - name: Set up Docker
      run: |
        docker info
        docker buildx create --use
      
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
    - name: Build and push Docker image
      run: |
        docker buildx build \
          --cache-from=type=registry,ref=ghcr.io/${{ github.repository }}/futures-trading-log:buildcache \
          --cache-to=type=registry,ref=ghcr.io/${{ github.repository }}/futures-trading-log:buildcache,mode=max \
          --tag ghcr.io/${{ github.repository }}/futures-trading-log:latest \
          --tag ghcr.io/${{ github.repository }}/futures-trading-log:${{ github.sha }} \
          --push \
          .
        
    - name: Run Tests
      run: |
        docker build -t futures-trading-log-test -f Dockerfile.test .
        docker run futures-trading-log-test